###
GET http://localhost:4004/odata/v4/stats/OrderInfo

### Add some Orders
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json

{"book_ID": 201, "quantity": 2}

### Add some Orders
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json

{"book_ID": 252, "quantity": 7}

### Add some Orders
POST http://localhost:4004/odata/v4/catalog/Orders
Content-Type: application/json

{"book_ID": 421, "quantity": 42}